CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  price_cents integer NOT NULL CHECK (price_cents > 0),
  stock integer NOT NULL CHECK (stock >= 0),
  symbol text NOT NULL,
  color text NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  shipping_address text NOT NULL,
  total_cents integer NOT NULL CHECK (total_cents > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id),
  product_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price_cents integer NOT NULL CHECK (unit_price_cents > 0)
);

INSERT INTO products (sku, name, category, description, price_cents, stock, symbol, color) VALUES
  ('LAMP-ARC', 'Arc Table Lamp', 'Lighting', 'A warm glow for slower evenings and focused mornings.', 249900, 12, '💡', 'peach'),
  ('MUG-CERAMIC', 'Ceramic Cup Set', 'Dining', 'Two everyday cups with a satisfying, handmade feel.', 99900, 20, '☕', 'sand'),
  ('THROW-LINEN', 'Linen Blend Throw', 'Textiles', 'A soft layer for your favorite reading corner.', 219900, 9, '🧶', 'lilac'),
  ('TRAY-BAMBOO', 'Bamboo Desk Tray', 'Workspace', 'A neat little home for all the things on your desk.', 129900, 16, '🗂️', 'sage'),
  ('CARAFE-GLASS', 'Ripple Glass Carafe', 'Dining', 'A simple table companion for water, flowers, or both.', 149900, 11, '🫗', 'blue'),
  ('TOTE-CANVAS', 'Everyday Canvas Tote', 'Lifestyle', 'A roomy companion for market days and more.', 179900, 18, '👜', 'pink'),
  ('CANDLE-AMBER', 'Amber Soy Candle', 'Lifestyle', 'A gentle, cozy scent in a reusable glass jar.', 89900, 14, '🕯️', 'cream'),
  ('CLOCK-QUIET', 'Quiet Wall Clock', 'Living', 'Clean lines and a calm presence for any room.', 199900, 7, '🕰️', 'mint')
ON CONFLICT (sku) DO NOTHING;
