apiVersion: v1
kind: ConfigMap
metadata:
  name: marrow-configmap
  namespace: marrow-ns
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: marrow_shop

  DB_HOST: postgres
  PORT: "5000"
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: marrow_shop

